# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

variables:
  imageName: '$(dockerId)/stanfordcorenlp'

jobs:
- job: login
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: docker login -u $(dockerId) -p $(pswd)
    displayName: 'login docker hub'

- job: arabic
  timeoutInMinutes: 90
  dependsOn:
  - login
  steps:
  - script: docker build -f Dockerfile -t $(imageName):3.9.2-arabic -t $(imageName):arabic .
    workingDirectory: "$(System.DefaultWorkingDirectory)/3.9.2/arabic"
    displayName: 'build 3.9.2 arabic'
  - script: docker push $(imageName)
    displayName: 'push docker'

- job: chinese
  timeoutInMinutes: 90
  dependsOn:
  - login
  steps:
  - script: docker build -f Dockerfile -t $(imageName):3.9.2-chinese -t $(imageName):chinese .
    workingDirectory: "$(System.DefaultWorkingDirectory)/3.9.2/chinese"
    displayName: 'build 3.9.2 chinese'
  - script: docker push $(imageName)
    displayName: 'push docker'

- job: english
  timeoutInMinutes: 90
  dependsOn:
  - login
  steps:
  - script: docker build -f Dockerfile -t $(imageName):3.9.2 -t $(imageName):3.9.2-english -t $(imageName):english -t $(imageName):latest .
    workingDirectory: "$(System.DefaultWorkingDirectory)/3.9.2/english"
    displayName: 'build 3.9.2 english'
  - script: docker push $(imageName)
    displayName: 'push docker'

- job: englishkbp
  timeoutInMinutes: 90
  dependsOn:
  - login
  steps:
  - script: docker build -f Dockerfile -t $(imageName):3.9.2-english-kbp -t $(imageName):english-kbp .
    workingDirectory: "$(System.DefaultWorkingDirectory)/3.9.2/english-kbp"
    displayName: 'build 3.9.2 english-kbp'
  - script: docker push $(imageName)
    displayName: 'push docker'


- job: french
  timeoutInMinutes: 90
  dependsOn:
  - login
  steps:
  - script: docker build -f Dockerfile -t $(imageName):3.9.2-french -t $(imageName):french .
    workingDirectory: "$(System.DefaultWorkingDirectory)/3.9.2/french"
    displayName: 'build 3.9.2 french'
  - script: docker push $(imageName)
    displayName: 'push docker'

- job: german
  timeoutInMinutes: 90
  dependsOn:
  - login
  steps:
  - script: docker build -f Dockerfile -t $(imageName):3.9.2-german -t $(imageName):german .
    workingDirectory: "$(System.DefaultWorkingDirectory)/3.9.2/german"
    displayName: 'build 3.9.2 german'
  - script: docker push $(imageName)
    displayName: 'push docker'


- job: spanish
  timeoutInMinutes: 90
  dependsOn:
  - login
  steps:
  - script: docker build -f Dockerfile -t $(imageName):3.9.2-spanish -t $(imageName):spanish .
    workingDirectory: "$(System.DefaultWorkingDirectory)/3.9.2/spanish"
    displayName: 'build 3.9.2 spanish'
  - script: docker push $(imageName)
    displayName: 'push docker'





